substitutions:
  device_name: nspanel_01
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"
  nextion_update_url: "http://192.168.1.2/nspanel_eu.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
#    url: https://github.com/asperkins/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s
